export const MODE_META = {
  START_MODE: {
    label: 'START MODE',
    headline: 'Build English you can use immediately.',
    description: 'Core conversational reflexes for everyday situations.',
  },
  RESPONSE_MODE: {
    label: 'RESPONSE MODE',
    headline: 'Turn familiar English into faster responses.',
    description: 'Quick answers, expansion and conversation bridges.',
  },
  CONVERSATION_MODE: {
    label: 'CONVERSATION MODE',
    headline: 'Keep the conversation moving.',
    description: 'Follow-up questions, stories and connected responses.',
  },
  FLUENCY_MODE: {
    label: 'FLUENCY MODE',
    headline: 'Train rhythm, speed and natural conversational chunks.',
    description: 'Flexible language for spontaneous conversation.',
  },
  NATIVE_FLOW: {
    label: 'NATIVE FLOW',
    headline: 'Add nuance, precision and personality.',
    description: 'Advanced reactions, subtle meaning and conversational control.',
  },
};

export const CURRICULUM = {
  START_MODE: [
    {
      key: 'start-01',
      title: 'Introduce Yourself',
      subtitle: 'Build your first automatic conversation blocks.',
      focus: 'First introductions',
      phrase: "Hi, I'm {{name}}. I'm from Venezuela. I work in marketing. What about you?",
      chunks: ["Hi, I'm {{name}}.", "I'm from Venezuela.", "I work in marketing.", 'What about you?'],
      buildPrompt: 'Complete this with your own information:',
      buildStem: "I'm from",
      quickPrompt: 'Someone asks: “What do you do?” Give a short, natural answer.',
      rolePrompt: 'You meet someone at an international event. They say: “Hi! Nice to meet you. Where are you from?”',
      roleOptions: ['I’m from Venezuela. What about you?', 'Venezuela is my country from.', 'I am having Venezuela.'],
      best: 0,
      speakPrompt: 'Introduce yourself for about 30 seconds. Say your name, where you are from, what you do, and finish with “What about you?”',
      power: ['Hi, I’m…', 'I’m from…', 'I work in…', 'What about you?'],
    },
    {
      key: 'start-02',
      title: 'Talk About Your Day',
      subtitle: 'Use simple time phrases to describe your routine.',
      focus: 'Daily routine',
      phrase: 'I usually start work in the morning. In the afternoon, I take a short break.',
      chunks: ['I usually start work in the morning.', 'In the afternoon…', 'I take a short break.'],
      buildPrompt: 'Complete this with something true about your day:',
      buildStem: 'I usually',
      quickPrompt: 'Someone asks: “What do you do in the morning?” Answer with one complete sentence.',
      rolePrompt: 'A classmate says: “My mornings are always busy. How about yours?”',
      roleOptions: ['Mine are busy too. I usually start work early.', 'Morning I am busy yes.', 'I morning working.'],
      best: 0,
      speakPrompt: 'Talk for about 30 seconds about your morning, afternoon and evening.',
      power: ['I usually…', 'In the morning…', 'In the afternoon…', 'At night…'],
    },
    {
      key: 'start-03',
      title: 'Ask Simple Questions',
      subtitle: 'Build useful questions that keep a basic conversation alive.',
      focus: 'Questions',
      phrase: 'Where do you live? What do you do? What do you like to do?',
      chunks: ['Where do you live?', 'What do you do?', 'What do you like to do?'],
      buildPrompt: 'Turn this into your own simple question:',
      buildStem: 'What do you',
      quickPrompt: 'You want to know someone’s favorite food. Ask one natural question.',
      rolePrompt: 'You are meeting a new person. Choose the best next question.',
      roleOptions: ['What do you like to do on weekends?', 'You weekend what doing?', 'Weekend good?'],
      best: 0,
      speakPrompt: 'Ask four simple questions you could use when meeting someone new.',
      power: ['Where do you…?', 'What do you…?', 'Do you like…?', 'How about you?'],
    },
    {
      key: 'start-04',
      title: 'Handle Everyday Needs',
      subtitle: 'Use survival English for common situations.',
      focus: 'Everyday English',
      phrase: 'Excuse me, could you help me? I’m looking for the restroom.',
      chunks: ['Excuse me…', 'Could you help me?', 'I’m looking for…'],
      buildPrompt: 'Complete the request with something you might need:',
      buildStem: 'I’m looking for',
      quickPrompt: 'You need the Wi-Fi password. Ask for it politely.',
      rolePrompt: 'You are in a café and need help. What sounds natural?',
      roleOptions: ['Excuse me, could you help me with the Wi-Fi?', 'Help Wi-Fi me please now.', 'I need you Wi-Fi.'],
      best: 0,
      speakPrompt: 'Imagine you are in a new city. Ask for help with two different things.',
      power: ['Excuse me…', 'Could you help me?', 'I’m looking for…', 'Thank you.'],
    },
    {
      key: 'start-05',
      title: 'Your First Mini Conversation',
      subtitle: 'Put introductions, questions and everyday responses together.',
      focus: 'Mini conversation',
      phrase: 'Nice to meet you. I’m from Venezuela. What about you? Oh, really? That’s great.',
      chunks: ['Nice to meet you.', 'What about you?', 'Oh, really?', 'That’s great.'],
      buildPrompt: 'Add one detail about yourself after this opener:',
      buildStem: 'Nice to meet you. I',
      quickPrompt: 'Someone says: “I’m from Colombia.” React and ask one question.',
      rolePrompt: 'A new friend says: “I work in design.” What is the best response?',
      roleOptions: ['Oh, really? That’s interesting. What kind of design?', 'Design yes.', 'I am not design.'],
      best: 0,
      speakPrompt: 'Do a 45-second mini conversation by yourself: introduce yourself, react to an imaginary answer, ask two questions and close politely.',
      power: ['Nice to meet you.', 'Oh, really?', 'That’s interesting.', 'See you later.'],
    },
  ],

  RESPONSE_MODE: [
    {
      key: 'response-01',
      title: 'Answer Without Freezing',
      subtitle: 'Turn familiar English into quicker responses.',
      focus: 'Quick answers',
      phrase: 'Actually, I work in marketing. I usually help small businesses. What about you?',
      chunks: ['Actually, I work in marketing.', 'I usually help small businesses.', 'What about you?'],
      buildPrompt: 'Complete this with something true about your routine:',
      buildStem: 'Usually, I',
      quickPrompt: 'Someone asks: “What do you usually do on weekends?” Answer in one or two sentences.',
      rolePrompt: 'A new contact asks: “So, what have you been working on lately?”',
      roleOptions: ['Actually, I’ve been working on a new project. What about you?', 'I working lately project.', 'Yes, lately is good.'],
      best: 0,
      speakPrompt: 'Talk for about 30 seconds about what you do during a normal week. Use “usually” and ask one question back.',
      power: ['Actually…', 'Usually, I…', 'Let me think…', 'What about you?'],
    },
    {
      key: 'response-02',
      title: 'Expand Your Answer',
      subtitle: 'Move from one-word answers to useful conversational responses.',
      focus: 'Answer expansion',
      phrase: 'Yeah, I do. I started a few years ago, and I really enjoy it.',
      chunks: ['Yeah, I do.', 'I started a few years ago.', 'I really enjoy it.'],
      buildPrompt: 'Expand a short yes/no answer with one reason:',
      buildStem: 'Yeah, I do. I',
      quickPrompt: 'Someone asks: “Do you like traveling?” Give a two-sentence answer.',
      rolePrompt: 'Someone asks: “Do you cook often?”',
      roleOptions: ['Yeah, I do. I usually cook at home during the week.', 'Yes.', 'Cooking I yes often.'],
      best: 0,
      speakPrompt: 'Answer three yes/no questions out loud, adding one detail after each answer.',
      power: ['Yeah, I do.', 'Not really.', 'Most of the time…', 'It depends.'],
    },
    {
      key: 'response-03',
      title: 'Yesterday, Today, Tomorrow',
      subtitle: 'Move naturally between simple time frames.',
      focus: 'Time shifts',
      phrase: 'Yesterday was busy. Today is better, and tomorrow I’m meeting a client.',
      chunks: ['Yesterday was busy.', 'Today is better.', 'Tomorrow I’m meeting a client.'],
      buildPrompt: 'Complete this with a plan for tomorrow:',
      buildStem: 'Tomorrow, I’m',
      quickPrompt: 'What did you do yesterday evening? Answer in two sentences.',
      rolePrompt: 'A friend asks: “What are you doing tomorrow?”',
      roleOptions: ['I’m meeting a client in the morning, then I’m free.', 'Tomorrow I did meeting.', 'I do tomorrow yesterday.'],
      best: 0,
      speakPrompt: 'Talk for 40 seconds: one thing from yesterday, one thing happening today and one plan for tomorrow.',
      power: ['Yesterday, I…', 'Today, I’m…', 'Tomorrow, I’m…', 'Later, I’m going to…'],
    },
    {
      key: 'response-04',
      title: 'Bridge the Conversation',
      subtitle: 'Use small phrases to keep speaking while you think.',
      focus: 'Conversation bridges',
      phrase: 'Let me think for a second. I’d say it depends, but usually I prefer working early.',
      chunks: ['Let me think for a second.', 'I’d say it depends.', 'Usually, I prefer…'],
      buildPrompt: 'Use a bridge before giving your opinion:',
      buildStem: 'Let me think.',
      quickPrompt: 'Someone asks: “What is the best city you’ve visited?” Use a bridge, then answer.',
      rolePrompt: 'You need two seconds to think before answering a question.',
      roleOptions: ['That’s a good question. Let me think for a second.', 'Wait because my English.', 'I cannot answer now English.'],
      best: 0,
      speakPrompt: 'Answer three unexpected questions and begin each response with a different conversation bridge.',
      power: ['Let me think.', 'That’s a good question.', 'I’d say…', 'It depends.'],
    },
    {
      key: 'response-05',
      title: 'Three-Minute Response Flow',
      subtitle: 'Connect quick answers into a short natural exchange.',
      focus: 'Short conversation',
      phrase: 'Pretty good, actually. I’ve been busy with work, but things are going well.',
      chunks: ['Pretty good, actually.', 'I’ve been busy with work.', 'Things are going well.'],
      buildPrompt: 'Add one detail after this response:',
      buildStem: 'Pretty good, actually.',
      quickPrompt: 'Someone asks: “How have you been?” Give a natural expanded answer.',
      rolePrompt: 'A friend says: “It’s been a while! How are things?”',
      roleOptions: ['Pretty good, actually. I’ve been busy with work. How about you?', 'I am fine thanks end.', 'Things am good since while.'],
      best: 0,
      speakPrompt: 'Speak for about 60 seconds as if you were catching up with an old friend. Give details and ask at least two questions back.',
      power: ['Pretty good, actually.', 'I’ve been…', 'How about you?', 'What have you been up to?'],
    },
  ],

  CONVERSATION_MODE: [
    {
      key: 'conversation-01',
      title: 'Keep It Going',
      subtitle: 'React, add detail and ask the next question.',
      focus: 'Follow-up questions',
      phrase: 'Really? That sounds interesting. How did you get into that?',
      chunks: ['Really?', 'That sounds interesting.', 'How did you get into that?'],
      buildPrompt: 'Add a natural follow-up question after this reaction:',
      buildStem: 'That sounds interesting.',
      quickPrompt: 'A friend says: “I just got back from Mexico.” Respond and ask a follow-up question.',
      rolePrompt: 'Someone tells you: “I started my own business last year.”',
      roleOptions: ['Really? That’s great. What made you decide to start it?', 'Business last year is beginning.', 'Okay. End of conversation.'],
      best: 0,
      speakPrompt: 'Talk for about 40 seconds about a recent experience, then imagine the listener reacts. Add one follow-up question.',
      power: ['Really?', 'How was it?', 'What happened next?', 'That reminds me of…'],
    },
    {
      key: 'conversation-02',
      title: 'Tell a Short Story',
      subtitle: 'Structure an experience so people can follow it easily.',
      focus: 'Storytelling',
      phrase: 'So, last weekend I went out with some friends. At first everything was normal, and then something funny happened.',
      chunks: ['So, last weekend…', 'At first…', 'Then something happened.'],
      buildPrompt: 'Begin a short story with a clear time reference:',
      buildStem: 'So, last',
      quickPrompt: 'Tell someone what happened the last time you were late.',
      rolePrompt: 'Which opening makes a story easiest to follow?',
      roleOptions: ['So, last Friday I was on my way home when…', 'Story is Friday and home.', 'I explain something happened many.'],
      best: 0,
      speakPrompt: 'Tell a 60-second story with a beginning, one change or surprise, and a clear ending.',
      power: ['So, last…', 'At first…', 'Then…', 'In the end…'],
    },
    {
      key: 'conversation-03',
      title: 'React Before You Answer',
      subtitle: 'Show that you are listening before adding your own idea.',
      focus: 'Natural reactions',
      phrase: 'No way! I didn’t know that. That must have been exciting.',
      chunks: ['No way!', 'I didn’t know that.', 'That must have been exciting.'],
      buildPrompt: 'React first, then add one comment:',
      buildStem: 'Wow,',
      quickPrompt: 'Someone tells you they are moving to another country. React naturally.',
      rolePrompt: 'A friend says: “I got the job!”',
      roleOptions: ['That’s amazing! Congratulations. When do you start?', 'Job yes good.', 'I know job.'],
      best: 0,
      speakPrompt: 'Imagine three pieces of surprising news and respond to each with a reaction, comment and follow-up question.',
      power: ['No way!', 'That’s amazing.', 'I can imagine.', 'That must have been…'],
    },
    {
      key: 'conversation-04',
      title: 'Share Your Opinion',
      subtitle: 'Express a view and support it without stopping the flow.',
      focus: 'Opinions',
      phrase: 'Personally, I think working from home can be great because it gives people more flexibility.',
      chunks: ['Personally, I think…', 'It can be great because…', 'At the same time…'],
      buildPrompt: 'Give an opinion and one reason:',
      buildStem: 'Personally, I think',
      quickPrompt: 'What is your opinion about online learning? Give one reason.',
      rolePrompt: 'Someone asks: “Do you think social media is helpful?”',
      roleOptions: ['It can be helpful, especially for business, but I think it depends on how you use it.', 'Social media yes and no.', 'Helpful is because internet.'],
      best: 0,
      speakPrompt: 'Speak for 60 seconds about one topic you have a clear opinion on. Give two reasons and ask the listener what they think.',
      power: ['Personally, I think…', 'For me…', 'The main reason is…', 'What do you think?'],
    },
    {
      key: 'conversation-05',
      title: 'Five-Minute Conversation Challenge',
      subtitle: 'Combine reactions, stories, opinions and follow-up questions.',
      focus: 'Conversation stamina',
      phrase: 'That reminds me of something similar that happened to me. Have I ever told you about it?',
      chunks: ['That reminds me of…', 'Something similar happened to me.', 'Have I ever told you about it?'],
      buildPrompt: 'Connect someone else’s idea to your own experience:',
      buildStem: 'That reminds me of',
      quickPrompt: 'A friend mentions a difficult trip. Connect it to one of your own experiences.',
      rolePrompt: 'Which response creates the most room for conversation?',
      roleOptions: ['That reminds me of a trip I took last year. The same thing happened. What did you do next?', 'I also traveled.', 'Trips are sometimes difficult.'],
      best: 0,
      speakPrompt: 'Speak for 90 seconds. React to an imaginary comment, tell a short related story, give an opinion and finish with a follow-up question.',
      power: ['That reminds me of…', 'Speaking of that…', 'In my experience…', 'What happened next?'],
    },
  ],

  FLUENCY_MODE: [
    {
      key: 'fluency-01',
      title: 'Sound More Natural',
      subtitle: 'Use rhythm, reactions and flexible conversational chunks.',
      focus: 'Natural chunks',
      phrase: 'Now that you mention it, I’ve actually been thinking about that too.',
      chunks: ['Now that you mention it…', 'I’ve actually been thinking about that too.', 'That makes sense.'],
      buildPrompt: 'Use this opener to add your own idea:',
      buildStem: 'Now that you mention it,',
      quickPrompt: 'Someone says: “Working from home is more productive for everyone.” React naturally and add your view.',
      rolePrompt: 'A colleague says: “I’m thinking about changing careers completely.”',
      roleOptions: ['That’s a big move. What’s making you think about the change?', 'Career completely change is maybe.', 'You must change it immediately.'],
      best: 0,
      speakPrompt: 'Speak for about 45 seconds about a decision you have been considering. Use at least two natural transition phrases.',
      power: ['Now that you mention it…', 'That makes sense.', 'Pretty much.', 'By the way…'],
    },
    {
      key: 'fluency-02',
      title: 'Tell Better Stories',
      subtitle: 'Use pacing, emphasis and detail to make stories easier to follow.',
      focus: 'Story rhythm',
      phrase: 'The funny thing is, I almost didn’t go. Looking back, I’m really glad I did.',
      chunks: ['The funny thing is…', 'I almost didn’t go.', 'Looking back…'],
      buildPrompt: 'Add a reflective ending to an experience:',
      buildStem: 'Looking back,',
      quickPrompt: 'Tell someone about a decision that turned out better than expected.',
      rolePrompt: 'Which phrase naturally highlights the surprising part of a story?',
      roleOptions: ['The funny thing is, I wasn’t even planning to be there.', 'The story funny is this.', 'Surprise was me there.'],
      best: 0,
      speakPrompt: 'Tell a 75-second story with one surprising detail and a reflective ending.',
      power: ['The funny thing is…', 'Believe it or not…', 'Turns out…', 'Looking back…'],
    },
    {
      key: 'fluency-03',
      title: 'Agree, Disagree, Add Nuance',
      subtitle: 'Respond to opinions without sounding rigid.',
      focus: 'Discussion',
      phrase: 'I see your point. I agree to an extent, although I think it depends on the situation.',
      chunks: ['I see your point.', 'I agree to an extent.', 'It depends on the situation.'],
      buildPrompt: 'Acknowledge the other view before adding yours:',
      buildStem: 'I see your point,',
      quickPrompt: 'React to: “Everyone should work in an office.” Give a nuanced answer.',
      rolePrompt: 'A colleague shares an idea you partly agree with.',
      roleOptions: ['I see your point. I agree with the goal, although I’d approach it a little differently.', 'I disagree because wrong.', 'Yes but no.'],
      best: 0,
      speakPrompt: 'Speak for 60 seconds about a topic where your view is mixed. Acknowledge another perspective and explain your position.',
      power: ['I see your point.', 'To an extent…', 'At the same time…', 'It depends on…'],
    },
    {
      key: 'fluency-04',
      title: 'Handle Fast English',
      subtitle: 'Recover smoothly when you miss a detail.',
      focus: 'Repair strategies',
      phrase: 'Sorry, I caught most of that, but what did you say right after “the meeting”?',
      chunks: ['I caught most of that…', 'What did you say right after…?', 'Could you run that by me again?'],
      buildPrompt: 'Ask for one specific missing detail:',
      buildStem: 'Sorry, what did you say',
      quickPrompt: 'You understood the topic but missed the final detail. Ask naturally.',
      rolePrompt: 'Someone spoke quickly and you missed one part.',
      roleOptions: ['I caught the first part. Could you run the last bit by me again?', 'Repeat all English.', 'I understand nothing because fast.'],
      best: 0,
      speakPrompt: 'Practice three repair phrases out loud, each one for a different situation: one word, one detail and the whole sentence.',
      power: ['I caught most of that.', 'What was that last part?', 'Could you run that by me again?', 'Did you say…?'],
    },
    {
      key: 'fluency-05',
      title: 'Fifteen-Minute Flow',
      subtitle: 'Combine stories, reactions, opinions and repair strategies.',
      focus: 'Conversation flow',
      phrase: 'That’s interesting. I hadn’t thought about it that way. Actually, that reminds me of something.',
      chunks: ['That’s interesting.', 'I hadn’t thought about it that way.', 'That reminds me of…'],
      buildPrompt: 'Connect a reaction to a related idea:',
      buildStem: 'That’s interesting.',
      quickPrompt: 'React to a new idea, connect it to your experience and ask a question.',
      rolePrompt: 'Which response creates the smoothest transition to your own story?',
      roleOptions: ['That’s interesting. Actually, that reminds me of something that happened at work last month.', 'Interesting. My story now.', 'I will change subject.'],
      best: 0,
      speakPrompt: 'Speak for 90 seconds as part of an imaginary discussion. React, expand, tell a short story and ask a thoughtful question.',
      power: ['I hadn’t thought about it that way.', 'That reminds me of…', 'Speaking of which…', 'How do you see it?'],
    },
  ],

  NATIVE_FLOW: [
    {
      key: 'native-01',
      title: 'Precision & Personality',
      subtitle: 'Train nuance, spontaneous reactions and conversational control.',
      focus: 'Nuanced responses',
      phrase: 'I get where you’re coming from. Off the top of my head, I’d probably approach it differently.',
      chunks: ['I get where you’re coming from.', 'Off the top of my head…', 'I’d probably approach it differently.'],
      buildPrompt: 'Use this phrase to introduce a spontaneous opinion:',
      buildStem: 'Off the top of my head,',
      quickPrompt: 'Someone says: “AI will replace most creative jobs within five years.” Give a nuanced response.',
      rolePrompt: 'During a meeting someone proposes a plan you partly agree with.',
      roleOptions: ['I get where you’re coming from. I’d tweak a couple of things before moving forward.', 'I am disagree with all your plan.', 'Your idea is totally impossible.'],
      best: 0,
      speakPrompt: 'Speak for about 60 seconds about an idea you have mixed feelings about. Use nuance, one spontaneous reaction and one follow-up question.',
      power: ['I get where you’re coming from.', 'Off the top of my head…', 'That caught me off guard.', 'I’d put it this way…'],
    },
    {
      key: 'native-02',
      title: 'Disagree Without Friction',
      subtitle: 'Challenge an idea while protecting the relationship and the flow.',
      focus: 'Diplomatic disagreement',
      phrase: 'I see the logic, although I’m not entirely convinced that would solve the underlying issue.',
      chunks: ['I see the logic…', 'I’m not entirely convinced…', 'The underlying issue…'],
      buildPrompt: 'Challenge an idea with one precise concern:',
      buildStem: 'I see the logic, although',
      quickPrompt: 'A colleague wants to cut a project timeline in half. Respond diplomatically.',
      rolePrompt: 'Which answer challenges the idea while keeping the discussion constructive?',
      roleOptions: ['I see the appeal, but I’m not sure the timeline leaves enough room for testing.', 'That timeline is bad.', 'You are wrong about the project.'],
      best: 0,
      speakPrompt: 'Give a 60-second response to a proposal you disagree with. Acknowledge the logic, identify one concern and suggest an alternative.',
      power: ['I see the logic.', 'I’m not entirely convinced…', 'My concern would be…', 'What if we…?'],
    },
    {
      key: 'native-03',
      title: 'Think Out Loud',
      subtitle: 'Sound composed while building an answer in real time.',
      focus: 'Spontaneous thinking',
      phrase: 'If I think out loud for a second, the bigger question might be what we’re optimizing for.',
      chunks: ['If I think out loud for a second…', 'The bigger question might be…', 'What are we optimizing for?'],
      buildPrompt: 'Use a thinking phrase before reframing the problem:',
      buildStem: 'If I think out loud for a second,',
      quickPrompt: 'You are asked an unexpected strategic question. Begin your answer without rushing.',
      rolePrompt: 'You need time to formulate a high-level answer in a meeting.',
      roleOptions: ['Let me think out loud for a second. I think the real trade-off is speed versus consistency.', 'I do not know, wait.', 'Question is difficult for me now.'],
      best: 0,
      speakPrompt: 'Answer an unexpected question for 75 seconds. Think out loud, reframe the issue and arrive at a clear conclusion.',
      power: ['Let me think out loud…', 'The bigger question is…', 'The way I see it…', 'If I had to narrow it down…'],
    },
    {
      key: 'native-04',
      title: 'Tell Stories With Subtext',
      subtitle: 'Add implication, tone and reflection beyond the basic events.',
      focus: 'Advanced storytelling',
      phrase: 'At the time I didn’t think much of it, but in hindsight that conversation changed the way I approached the whole project.',
      chunks: ['At the time…', 'I didn’t think much of it.', 'In hindsight…'],
      buildPrompt: 'Add a reflective layer after describing an event:',
      buildStem: 'In hindsight,',
      quickPrompt: 'Describe a small moment that later turned out to matter more than you expected.',
      rolePrompt: 'Which ending adds reflection rather than just finishing the chronology?',
      roleOptions: ['In hindsight, that was probably the moment I realized the project needed a different direction.', 'Then the project finished.', 'That was the end of event.'],
      best: 0,
      speakPrompt: 'Tell a 90-second story where the meaning of an event becomes clearer only at the end.',
      power: ['At the time…', 'I didn’t think much of it.', 'In hindsight…', 'What I took from that was…'],
    },
    {
      key: 'native-05',
      title: 'Lead the Conversation',
      subtitle: 'Summarize, redirect and invite the next contribution.',
      focus: 'Conversational leadership',
      phrase: 'So, if I’m hearing you correctly, we agree on the goal. The open question is how we get there.',
      chunks: ['If I’m hearing you correctly…', 'We agree on the goal.', 'The open question is…'],
      buildPrompt: 'Summarize agreement and identify the remaining question:',
      buildStem: 'If I’m hearing you correctly,',
      quickPrompt: 'Two people have been discussing a problem for several minutes. Summarize and move the conversation forward.',
      rolePrompt: 'Which response demonstrates conversational leadership?',
      roleOptions: ['It sounds like we agree on the outcome. Maybe the next question is which option gets us there with the least risk.', 'Everybody talked. Next.', 'I will decide now for all.'],
      best: 0,
      speakPrompt: 'Lead a 90-second imaginary discussion: summarize two viewpoints, identify common ground, frame the open question and invite the next response.',
      power: ['If I’m hearing you correctly…', 'It sounds like we agree on…', 'The open question is…', 'How would you approach that?'],
    },
  ],
};

export function getModeSessions(mode) {
  return CURRICULUM[mode] || CURRICULUM.START_MODE;
}

export function getSession(mode, sessionKey) {
  return getModeSessions(mode).find((session) => session.key === sessionKey) || null;
}

export function getSessionIndex(mode, sessionKey) {
  return getModeSessions(mode).findIndex((session) => session.key === sessionKey);
}
